#!/bin/bash
# Cyberkryption's original project
# Don't like me for this project, because the creator is cyberkryption, and it is he who deserves your recognition
# This script shows how versatile bash can be.
# WTFPL license
clear

# shameless taken from @g0tmilk kali os-scripts
#### (Cosmetic) Colour output
RED="\033[01;31m"      # Issues/Errors
GREEN="\033[01;32m"    # Success
YELLOW="\033[01;33m"   # Warnings/Information
BLUE="\033[01;34m"     # Heading
BOLD="\033[01;01m"     # Highlight
RESET="\033[00m"       # Normal

#also shamelesly ganked from a stack overflow post at http://stackoverflow.com/questions/10458743/bash-reading-text-from-a-string-one-character-at-a-time-with-whitespace
# ascii art generated by Jp2a program by Christian Stigen Larsen at https://csl.name/jp2a/

function typewriter
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${text:$i:1}"
        sleep ${delay}
    done
}

function typewriter_red
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${RED}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_yellow
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${YELLOW}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_green
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${GREEN}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_blue
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${BLUE}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

function typewriter_bold
{
    text="$1"
    delay="$2"

    for i in $(seq 0 $(expr length "${text}")) ; do
        echo -e -n "${BOLD}${text:$i:1}${RESET}"
        sleep ${delay}
    done
}

clear
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo # <-- Just for a newline
echo -e "$RED;kkk;              .:lxkOOOOkxo:.         .;ldkOOOOOxdc,.     dkkk.      .:oxkOOOOkxo:'           :Oo           :kkk'            :kkk'     'coxOOOOOkxoc,."   
echo -e "$RESET:OOO;            :kOOOo:,'',:okOOk:     ,xOOOo:,''',:okOx.    kOOO.    :kOOkl;,''';cdOOo        .dOOOk'         cOOO,            cOOO,   .kOOx:,''',;:lxOl."  
echo -e "$RED:OOO;           dOOO:          cOOOx   :OOOo.         .'.     kOOO.   dOOO:           .        ;OOOxOOOc        cOOO,            cOOO,   ,OOOkl:;,,'..."      
echo -e "$RESET:OOO;          .OOOx            OOOO.  xOOO.     oOOOOOOOd    kOOO.  .OOOk                    oOOO: ,OOOx.      cOOO,            cOOO,    .:okOOOOOOOOOOd;"   
echo -e "$RED:OOO;           oOOOl.        .lOOOd   ;OOOd.    .....kOOd    kOOO.   lOOOl          ..     'xOOOo,,,lOOOO:     cOOO,            cOOO,     .    .....,dOOO;"  
echo -e "$RESET:OOOdccccccccc.  ;xOOOdc:;;;cdOOOx,     .oOOOxl:;;;:ldOOOl    kOOO.    ,xOOOdc:;;;:lxOOd   lOOOOkkkkkkkkOOOd.   cOOOoccccccccc.  cOOO,   ;OOkoc:;,;;:lkOOx."  
echo -e "$RED,ddddddddddddd'    .,codxkkkxoc,.          ':odxkkkxdl:'      oddd.      .,coxkkkkxoc;.  .ldddc         ;dddd.  ;ddddddddddddd.  ;ddd'    .,codxkkkkxdl;."    

sleep 1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_bold "                                                                           Presents...." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_bold "                                                           A Star Wars themed hacking challenge for fun." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_bold "                                                                  The story so far................" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
sleep 1
clear

echo -e -n "MMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMcXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMdOWMMMWNXXXXNWMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMWKxdook0kdxxkxxollkKKXMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMNK0koooodxxdoldxxxxddddooodO0XWMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMWKKxollccl:olddxkxkOO0KK0xoooollcllodOWMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMWd',d,llxl;;:::cllooddddodcclo:cc,;cdoc;dNWMMMMMMMM\r\n"
echo -e -n "MMMMMMM;  .'.';;,..;cl;;cllo;,':,'''..oc.......lx,lMMMMMMM\r\n"
echo -e -n "MMMMMMX   '...... .c'.:..'.'........ .. .     ..'. NMMMMMM\r\n"
echo -e -n "MMMMMMMc       ..     ..............      ...     :MMMMMMM\r\n"
echo -e -n "MMMMMMMMk,       .                          .    .0MMMMMMM\r\n"
echo -e -n "MMMMMMMMMMOxOOOOkdoc.                .:coxOOOK0,;oxOKKNMMM\r\n"
echo -e -n "MMMMMMMMWK000k00Okxd;.................ooodxkKNWd..'oKXWMMM\r\n"
echo -e -n "MMMMWkoc;,',',,,,,;:clddxxkkkkkxdllc;;,;;::cc:::;;;cOWMMMM\r\n"
echo -e -n "MMMMKl,............',,;:;;;;:;;;;,,,,,'''..........':xMMMM\r\n"
echo -e -n "MMMMW;....................'.............   ...     .'NMMMM\r\n"
echo -e -n "MMMMMk.................................. .....   .'.dMMMMM\r\n"
echo -e -n "MMMMMMK'............................. .  .....  .. ;WMMMMM\r\n"
echo -e -n "MMMMMMMk'............................ . ......  ..;WMMMMMM\r\n"
echo -e -n "MMMMMMMMN0xlc,.......................   ...  ,xxkNMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMM0c . :d:'...  ..........        .NMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMW.....,MMx..   ........ ... ,.   lMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMN,...;WMMWNOc..........;NMNNO' ..OMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMd... oWMMMMM0kc........ oNMMMX,,;clONMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMk.;::l:cdo,..lWd,......  oMMMMMkooxo:'';dXMMM\r\n"
echo -e -n "MMMMMMMMMMMMMk.,KXdo0Oo,...XOlc......cXMMMMMMMNxxKWk.:WMMM\r\n"
echo -e -n "MMMMMMMMMMMMMO..XMMMNKKk...WMcKKc..',WMMMMMMMMMMMWOd.NMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMO..NMMMMMMO:..MMKcMo..'.OMMMMMMMMMMMMMdlMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMO.,MMMMMMMMN,'MMMoKN,...:MMMMMMMMMMMMX.0MMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMO.:MMMMMMMMX:,MMMMOM;....XMMMMMMMMMMMl,MMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMN:..kMMMMMMMX::MMMMxc.....0MMMMMMMMXol'lMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMK.;MMMMMMMM0;cMMM0,.....'MMMMMMMMNol:xNMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMl,MMMMMMMN;.lMWd...'..kNMMMMMMMMMWNMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMK.NMMMMM0.,..k,:o0o. ;MMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMM;xMMMMW,kO..,OMWl: .kMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMx,MMMMMM0:.'KMW:x: cMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMN.0MMMMK;..XMWOl..  ,MMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMW'lWMMk....dklW0:..,dMx:codxxkOXMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMo..;WXl;'...'xOKc.WMO...xXXNMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMW,'o0MMMMMWXKOko..;;...,WMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMM0KMMMMMMMMMMMN'.XMWk.;MMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo .kMN,.KMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl ..K0kKMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN. .xMMMMMMMMMMMMMMMMMMMMMMM\r\n"

typewriter_red "Empire Malware Agent Manager: " .1
typewriter "Hoth Edition V1.0.9 Beta" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "Injecting Malware : " .1
typewriter "Empire Metasploit Implant - Credentials Recovery  and Recon 3.0" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_blue "[+] Acquiring process handle ...." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_blue "[+] Exploit - Malware Injected Successfully...Credential recovery beginning ...." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] Usernames ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] sploit,admin,vagrant,leah_organa,luke_skywalker,han_solo" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] artoo_detoo,c_three_pio,ben_kenobi,jarjar_binks,chewbacca,lando_calrissian" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_blue "[+] Passwords ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_blue "[+] use_the_f0rce,mandalorian1,not-a-slug12,hanShotFirst!,rwaaaaawr5,daddy_issues1,b@ckstab" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_blue "[+] mesah_p@ssw0rd,thats_no_moon,beep_b00p,sh00t-first,use_the_f0rce,help_me_obiw@n" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "[+] Usernames Yoda not found ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "[+] Searching ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] UDP Flood inbound - Flood protection starting ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] Exception Error in stack frame - 0x900x90Yoda" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_yellow "[+] Program terminated." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red " Implant communication lost - Empire Malware Agent failed" .1
echo # <-- Just for a newline
echo # <-- Just for a newline

clear
typewriter " Meanwhile, the Empire is not happy and is holding a meeting with Lord Vader.......... " .1
echo # <-- Just for a newline
echo # <-- Just for a newline

typewriter_yellow "[+] Connecting to : 13.37.13.37.." .1
echo # <-- Just for a newline
echo # <-- Just for a newline

typewriter_yellow "[+] Generating encryption keys - Death Star Protocol - 4096 bits" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
sleep 1
typewriter_green "[+] Secure communications establishing ..." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
clear
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXKK00O0O0K0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOOkxdxxddoodollldllccccoxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMWX0kddxxxxdxxddxooddoolddlcc:llcc:::okKWMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMNKkkxdxkkxkxdxkxdxddxdoolcoxoccc;locc:c;;;;lOWMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMWKkkkxxkxOOkOkxkkkddxdxxdoolcoxxccoc;,'..',;;:;,'l0WMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMXOkO0Okkkk00OOOkkOkxddxdxkdooolodxool......'',;;cc:,',dNMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMXkkkO0OkOOO0OOOOOOkddddddxOkoooooolooo,.....''',::llloo;..lNMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMXOkkkOKOkOOOK0000K00O00OkkkxOxdocodoooll'.......';;cldxxdxo'.'dWMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMW0kkxxk00OOOOKKKKK0XK0000OOOOkOxxolddooooo:.........;loxxxxxxk;..'0MMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMNkxkxkkOK000K0KKKKKKKKN0KKOkOOkxkOdlooodxkoc;.........cxxxxxkxdk,...oWMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMXkxkkkk0KOOOKK00KK0KKKXX000OkOOOxk0dlddodxkdcoc'.......'dkxkxxxoxc....:NMMMMMMMMM\r\n"
echo -e -n "MMMMMMXkxxxkk0K0000N00KK00KK0NX0OOOOkkOxkOdddoodxxdclcc;'......cloddod:d:.....'NMMMMMMMM\r\n"
echo -e -n "MMMMMNxkdxkO0KKOOOKX00K0000K0NKOkOkOOOOxxOddooodxxdlllccc:,....';::lc;cc'......,WMMMMMMM\r\n"
echo -e -n "MMMMWxkxxxxkxK0kkOXX0KKOK000KN00kOkkOOkxxOddooloxxdlllc::::c:;,'''',,;,.''......cMMMMMMM\r\n"
echo -e -n "MMMMOdkdddddOKXKk0NXKKK0K000KNK0O0OOOOOkkOdddoodxxdlllc:::::cc:;;;,,,,'.''.......kMMMMMM\r\n"
echo -e -n "MMMNdxxdddxx0KXKKXWNNNWWWWWNXXKK00Okkkxxxxddddddddddddooollllccc:::;;,.'.'........WMMMMM\r\n"
echo -e -n "MMMOokxkOO00Okxxkkkkkkxxkxxxxxkkkkkxkxxxxddddooolccc:;:;;;,,,,,,,,,',,,,,'........xMMMMM\r\n"
echo -e -n "MMMxxkoloooodk0KKKKKKKKKKKKXX0O0OOOkOOkkxxkkxxxdddodolccc:c:::::::;;,''...........;MMMMM\r\n"
echo -e -n "MMWlcldkOOOOO0OOkOOOkkOOOkOKKkkkkkkxOOkxdoxxxdddoololc:::,;:;;,,,,,',.'''..........WMMMM\r\n"
echo -e -n "MMXdddddxxxkk0xxxkkOkkkkkkk00kkxxxxdOkxdoldxolllcccllc;;;,;;;;;,','''..'...........KMMMM\r\n"
echo -e -n "MMNcooddxxxkkOxxxkxkxkxxxxx00xxxdxxdkkoooodxolcccc:lc:;;;,;,,,,'.'.''..............0MMMM\r\n"
echo -e -n "MMN:ldoddxxxxkdodxxkxxddxdxOOxddodooxxllllodlccc:::lc;;;,,,,,''....'...............XMMMM\r\n"
echo -e -n "MMMccoloooddxkxooddxxolooodkOdodooolxxlllloocc:c::;c;,,,,,,,'',..'.'...............MMMMM\r\n"
echo -e -n "MMMd:lclloooddxloloodoloodoxxdoollllodllccllc:cc::;c,,,'',,,'''....'..............cMMMMM\r\n"
echo -e -n "MMM0::lcllloooxdooodxlllloldlld::cccccocc:c::;lc:;,;c:,,..''';'...................0MMMMM\r\n"
echo -e -n "MMMMc;lllcllloddllloxlcllccocco;;:::::l:::c;;;c:;;,;:;,,'.,'',...................;MMMMMM\r\n"
echo -e -n "MMMMK;;c::cl:cooo::clo:cccclc:c:,;;,;;c::;:;;,::;;,;:,','.'..'...................XMMMMMM\r\n"
echo -e -n "MMMMMd;;:c::c:lll:::coccccllllc:::::::cc;;;,;;:;,,,',,,,'''.''..................kMMMMMMM\r\n"
echo -e -n "MMMMMWl;;::::cccc;;:;:::cccccc:,;,;,;;::'''.',;;''..',,''''..'.................oMMMMMMMM\r\n"
echo -e -n "MMMMMMWc',;;;;;,::,;;;;::::;;:;,,'',,;;;''..',,,'...','..'....................dMMMMMMMMM\r\n"
echo -e -n "MMMMMMMWl.',,,,,,;;',,,;,,,,,;;,....',,;.....'''....'........................kMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMx'.',,,'',,','',''''',,'....'',...................................,KMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMX:..'..''....................'..................................oWMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMO,.......................................... ...............cXMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMk,..................................... .  .  ..........cKMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMM0c.................................... ............'dNMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMWx;. .................. ... ..      . .........l0MMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMNk:.                  .  ..     ....  ..,o0WMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMXkl,.                 .     ...':o0WMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoc;'...........',:ldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo -e -n "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n"
echo # <-- Just for a newline
typewriter_red "Death Star IRC Server V.101 : " .1
typewriter "Darkside Edition V9.26 Final." .1
echo # <-- Just for a newline
typewriter_red "Communications protocol : " .1
typewriter "IronFist SSH V2.0 protocol 3.0" .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "Awaiting Clients ...." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
sleep 1
typewriter_blue "<LordVader>" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_1 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_2 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
typewriter_blue "<Empire_3 >" .1
typewriter "  Connected." .1
echo # <-- Just for a newline
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Morning Cadets. I want the Rebel Alliance plans." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Our malware was detected by the Rebels due to an agent failing me. He is no longer with us." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " I feel this distrubance in the force was caused by Yoda. He has interferred in Imperial business for the last time." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Our malware did tell us that vital information is hidden in files on the Rebel Alliance servers called secrets.txt" .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " The Rebel Alliance will no doubt have increased their defenses, you will overcome them." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " The Rebel Alliance is using the 192.168.1.1 - 192.168.1.254 range for their network." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Malware Report: Rebel defenses detected at 192.168.1.1, 192.168.1.120, 192.168.1.130 and 192.168.1.251." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " DO NOT SCAN THEM, unless you want to incurr my wrath!!!" .1 
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " We have instructions for our new security tools on your desktop." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Report any tools related issues immediately to your designated handler." .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter_yellow " Bring me Yoda's plans NOW. DO NOT FAIL ME !!!!!! " .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter_red " Bring me Yoda's plans NOW. DO NOT FAIL ME !!!!!! " .1
echo # <-- Just for a newline
typewriter_red "<LordVader>" .1
typewriter " Out. Communication terminated." .1
echo # <-- Just for a newline
sleep 5
